import Link from "next/link";

export const metadata = { title: "Privacy Policy · TechTreasure" };

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" updated="September 18, 2026">
      <p>This Privacy Policy explains what TechTreasure collects, why we collect it, how we use it, when we share it, and the choices available to you. It applies to the TechTreasure website, dashboard, payment flow, redirector, and related services.</p>
      <LegalSection title="1. Information we collect"><ul><li><strong>Account data:</strong> email address, authentication identifiers, password hash handled by Supabase, language, plan, credit balances, and account timestamps.</li><li><strong>Content data:</strong> brands, logos, selected icons, batches, input rows, titles, descriptions, tags, images, source links, schedules, and rendered pins you provide or create.</li><li><strong>Payment data:</strong> Razorpay order/subscription/payment identifiers, plan, amount, status, and transaction timestamps. Razorpay processes payment credentials; TechTreasure does not store full card, UPI, or bank credentials.</li><li><strong>API key data:</strong> an optional Gemini API key you manually save. It is stored in your profile and used to make AI requests; never paste secrets into content fields.</li><li><strong>Technical data:</strong> IP address, browser/device information, logs, errors, cookies, security events, and redirect click data where needed for operation, fraud prevention, analytics, and accounting.</li></ul></LegalSection>
      <LegalSection title="2. How we use information"><ul><li>Authenticate users and protect accounts.</li><li>Render pins, store exports, process inputs, and provide dashboard features.</li><li>Apply plan limits, credits, subscriptions, trial eligibility, and refunds.</li><li>Send transactional messages such as confirmation, security, and service notices.</li><li>Detect abuse, fraud, unauthorized access, unsafe destinations, and technical faults.</li><li>Improve reliability and understand aggregate feature usage.</li><li>Meet legal, tax, accounting, dispute-resolution, and enforcement obligations.</li></ul></LegalSection>
      <LegalSection title="3. Service providers and international processing"><p>We use infrastructure and providers including Supabase, Razorpay, Google Gemini when you use AI, hosting/CDN services, image providers, and analytics or advertising providers used by the redirector. They receive only the information needed for their service and may process it in countries different from yours. Review their privacy notices separately.</p></LegalSection>
      <LegalSection title="4. Gemini API keys and AI data"><p>When you enable your own Gemini key, the relevant input is sent to Google Gemini using that key. Do not submit confidential, regulated, or third-party personal information unless you have a lawful basis and understand the provider’s terms. AI output is generated automatically and may be wrong. AI credits are currently coming soon; manual-key AI access is a separate feature state.</p></LegalSection>
      <LegalSection title="5. Storage, retention, and deletion"><p>We retain account, payment, security, and accounting records for as long as needed to provide the service and meet legal obligations. We retain content and rendered pins until you delete them or the account is closed, subject to backups and legal holds. You may request deletion or correction through the support channel published in the application. Deletion may not remove records we must retain for fraud, tax, disputes, or legal compliance.</p></LegalSection>
      <LegalSection title="6. Cookies and similar technology"><p>We use necessary cookies for authentication and secure sessions. The standalone redirector and advertising providers may use their own cookies, scripts, local storage, or similar technologies. Browser controls and provider opt-out tools may limit them, although disabling necessary cookies can prevent login or checkout.</p></LegalSection>
      <LegalSection title="7. Security"><p>We use access controls, row-level security, server-side secrets, HTTPS where provided, and provider security features. No internet service is perfectly secure. You are responsible for protecting your credentials and API keys and for reporting suspected compromise quickly.</p></LegalSection>
      <LegalSection title="8. Your choices and rights"><p>Depending on your location, you may have rights to access, correct, delete, restrict, object to, or export personal information, or withdraw consent where processing is consent-based. Requests may require identity verification and may be limited by law. Contact us through the support address shown in the application.</p></LegalSection>
      <LegalSection title="9. Children and changes"><p>The service is not intended for children who cannot legally agree to these terms. We may update this policy when the service, providers, or law changes. The revised date will appear at the top.</p></LegalSection>
      <p className="mt-8 text-sm text-neutral-500">This policy is a product privacy template, not legal advice. Add your legal business name, contact address, data-protection contact, retention periods, and jurisdiction-specific disclosures before launch.</p>
    </LegalPage>
  );
}

function LegalPage({ title, updated, children }: { title: string; updated: string; children: React.ReactNode }) { return <main className="mx-auto max-w-3xl px-6 py-10"><Link href="/" className="font-bold text-brand">TechTreasure</Link><h1 className="mt-8 text-3xl font-bold">{title}</h1><p className="mt-2 text-sm text-neutral-500">Last updated: {updated}</p><article className="prose prose-neutral mt-8 max-w-none space-y-6 text-sm leading-7">{children}</article></main>; }
function LegalSection({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="mb-2 text-lg font-semibold text-neutral-900">{title}</h2>{children}</section>; }
