import Link from "next/link";

export const metadata = { title: "Terms and Conditions · TechTreasure" };

export default function TermsPage() {
  return (
    <LegalPage title="Terms and Conditions" updated="September 18, 2026">
      <p>These Terms and Conditions govern your access to and use of TechTreasure, including the website, account, pin-generation tools, rendered images, exports, redirector, paid plans, and related services. By creating an account or using the service, you agree to these terms.</p>
      <LegalSection title="1. Who we are and how these terms work"><p>TechTreasure is a software service for preparing Pinterest content. References to “we”, “us”, and “our” mean TechTreasure. References to “you” mean the individual or organization using the service. If you use the service for an organization, you confirm that you have authority to bind that organization.</p><p>These terms, the <Link href="/legal/privacy">Privacy Policy</Link>, and the <Link href="/legal/payments">Payments Terms</Link> form the agreement between you and TechTreasure.</p></LegalSection>
      <LegalSection title="2. Eligibility and accounts"><ul><li>You must provide a valid email address and keep your login credentials confidential.</li><li>You are responsible for activity performed through your account.</li><li>You must be legally able to enter this agreement.</li><li>One person or organization may not create accounts to evade limits, trial restrictions, suspension, or payment obligations.</li><li>Notify us promptly if you believe your account has been accessed without permission.</li></ul></LegalSection>
      <LegalSection title="3. Acceptable use"><p>You may use TechTreasure only for lawful content and lawful destinations. You must not:</p><ul><li>Upload or generate content that infringes copyright, trademark, privacy, publicity, confidentiality, or other rights.</li><li>Use the service for fraud, phishing, impersonation, malware, spam, harassment, or deceptive advertising.</li><li>Submit unlawful, defamatory, hateful, sexually exploitative, or threatening material.</li><li>Use generated content to mislead people about news, endorsements, identities, or sources.</li><li>Attempt to bypass credit limits, payment controls, rate limits, authentication, or security controls.</li><li>Scrape, reverse engineer, overload, resell, or interfere with the service.</li><li>Use another person’s API key, payment method, account, or personal information without authorization.</li></ul></LegalSection>
      <LegalSection title="4. Your content and generated content"><p>You retain ownership of content you submit, subject to the rights needed for us to process it. You grant TechTreasure a limited, non-exclusive license to host, reproduce, transform, render, store, and transmit that content only to operate, secure, troubleshoot, and improve the service.</p><p>You are solely responsible for checking generated titles, descriptions, images, sources, links, facts, and legal compliance before publishing. AI output may be inaccurate, incomplete, duplicated, or unsuitable. TechTreasure does not guarantee originality, factual accuracy, reach, approval by Pinterest, monetization, or fitness for a particular campaign.</p></LegalSection>
      <LegalSection title="5. Credits, limits, and service availability"><p>Credits are usage units, not money, property, or a bank balance. Pin credits may be used only for eligible rendering and hosting actions. AI credits, when offered, may be subject to separate rules. Credits do not earn interest, cannot be transferred, and have no cash value.</p><p>Free credits, paid plan credits, trial credits, expiry, renewal, and limits are shown at purchase or in the application. We may impose fair-use, technical, security, or abuse limits. We may change plans prospectively with reasonable notice. The service may be unavailable for maintenance, provider outages, browser limitations, network failures, or events outside our control.</p></LegalSection>
      <LegalSection title="6. Third-party services"><p>TechTreasure relies on third parties such as Supabase, Razorpay, Google Gemini, image hosts, Iconify, and Pinterest. Their terms, privacy practices, availability, fees, and policies may apply independently. We are not responsible for third-party outages, account decisions, content moderation, API changes, or destination websites.</p></LegalSection>
      <LegalSection title="7. Intellectual property"><p>TechTreasure software, branding, layout, documentation, and service materials belong to TechTreasure or its licensors. Except for the limited right to use the service, no license is granted. You may export and use your own generated assets subject to your inputs, third-party rights, provider terms, and applicable law.</p></LegalSection>
      <LegalSection title="8. Suspension and termination"><p>We may suspend, restrict, or terminate access for non-payment, abuse, security risk, unlawful use, breach of these terms, provider requirements, or operational reasons. We may delete or retain data as described in the Privacy Policy and as needed for legal, security, accounting, or dispute purposes. You may stop using the service at any time; paid subscription cancellation and refunds are governed by the Payments Terms.</p></LegalSection>
      <LegalSection title="9. Disclaimers"><p>The service is provided on an “as available” and “as is” basis to the maximum extent permitted by law. We disclaim warranties of uninterrupted availability, error-free operation, accuracy, merchantability, non-infringement, fitness for a particular purpose, search ranking, Pinterest acceptance, revenue, or campaign performance.</p></LegalSection>
      <LegalSection title="10. Limitation of liability"><p>To the maximum extent permitted by law, TechTreasure will not be liable for indirect, incidental, special, consequential, exemplary, or lost-profit damages, loss of data, loss of goodwill, or loss caused by third-party services or published content. Our total liability for a claim relating to the service will not exceed the amount you paid to TechTreasure for the service in the three months before the event giving rise to the claim, except where applicable law does not allow that limitation.</p></LegalSection>
      <LegalSection title="11. Indemnity"><p>You agree to defend and indemnify TechTreasure and its service providers against claims, losses, liabilities, costs, and reasonable legal fees arising from your content, destination links, unlawful use, breach of these terms, or violation of another person’s rights.</p></LegalSection>
      <LegalSection title="12. Changes and governing law"><p>We may update these terms by posting a revised version. Continued use after the effective date means acceptance. The governing law, venue, and dispute process should be completed with the business’s registered jurisdiction before production launch. Contact us through the support address published in the application for questions or notices.</p></LegalSection>
      <p className="mt-8 text-sm text-neutral-500">This document is a product terms template, not legal advice. Have a qualified lawyer review it for your business, jurisdiction, consumer laws, tax rules, and payment/refund obligations.</p>
    </LegalPage>
  );
}

function LegalPage({ title, updated, children }: { title: string; updated: string; children: React.ReactNode }) { return <main className="mx-auto max-w-3xl px-6 py-10"><Link href="/" className="font-bold text-brand">TechTreasure</Link><h1 className="mt-8 text-3xl font-bold">{title}</h1><p className="mt-2 text-sm text-neutral-500">Last updated: {updated}</p><article className="prose prose-neutral mt-8 max-w-none space-y-6 text-sm leading-7">{children}</article></main>; }
function LegalSection({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="mb-2 text-lg font-semibold text-neutral-900">{title}</h2>{children}</section>; }
