import Link from "next/link";
import { PLAN_PRICES_INR, PLAN_CREDITS, TRIAL_PLAN } from "@/lib/plans";

export const metadata = { title: "Payments Terms · TechTreasure" };

export default function PaymentsPage() {
  return (
    <LegalPage title="Payments Terms" updated="September 18, 2026">
      <p>These Payments Terms explain how TechTreasure pricing, Razorpay checkout, recurring plans, credits, trial purchases, cancellations, refunds, taxes, and payment disputes work. They supplement the <Link href="/legal/terms">Terms and Conditions</Link>.</p>
      <LegalSection title="1. Prices and currency"><p>Prices are displayed in Indian Rupees (INR): Pro ₹{PLAN_PRICES_INR.pro}/month, Pro Plus ₹{PLAN_PRICES_INR.pro_plus}/month, Pro Max ₹{PLAN_PRICES_INR.pro_max}/month, and the one-time Lifetime Trial ₹{TRIAL_PLAN.priceInr}. Prices may exclude taxes or charges required by law or shown by Razorpay. The amount shown at checkout is the amount submitted to Razorpay.</p></LegalSection>
      <LegalSection title="2. What each plan provides"><ul><li>Free: {PLAN_CREDITS.free.toLocaleString("en-IN")} monthly pin credits.</li><li>Pro: {PLAN_CREDITS.pro.toLocaleString("en-IN")} pin credits each billing cycle.</li><li>Pro Plus: {PLAN_CREDITS.pro_plus.toLocaleString("en-IN")} pin credits each billing cycle.</li><li>Pro Max: displayed as Unlimited and currently controlled by a {PLAN_CREDITS.pro_max.toLocaleString("en-IN")} pin-credit monthly cap.</li><li>AI credits are coming soon and are not currently included as a purchasable allocation. AI currently requires a manually supplied Gemini API key.</li></ul><p>Credits are consumed only when the relevant operation succeeds, subject to the application’s current rules. Credits are not cash, cannot be transferred, and cannot be exchanged for a refund except where required by law.</p></LegalSection>
      <LegalSection title="3. Recurring subscriptions"><p>Paid plans are monthly subscriptions. By completing checkout, you authorize Razorpay and its supported payment method to charge the selected amount on each billing cycle until cancellation or termination. Razorpay may show its own mandate, authentication, retry, and notification screens. A plan change may take effect when Razorpay confirms the new subscription and our webhook records it.</p></LegalSection>
      <LegalSection title="4. ₹9 Lifetime Trial"><p>The Lifetime Trial costs ₹{TRIAL_PLAN.priceInr} once and grants {TRIAL_PLAN.pinCredits.toLocaleString("en-IN")} pin credits. It is available once per account, is not a subscription, and does not renew. We may reject repeat, fraudulent, duplicate, reversed, or chargeback-associated purchases. Trial credits remain subject to the account limits and service rules.</p></LegalSection>
      <LegalSection title="5. Checkout and payment processing"><p>Payments are processed by Razorpay. TechTreasure receives payment status and limited transaction identifiers, not your complete card, UPI, or bank credentials. You must use a payment method you are authorized to use and provide accurate billing information. A payment is not complete until Razorpay confirms it and TechTreasure verifies the relevant signature or webhook event.</p></LegalSection>
      <LegalSection title="6. Failed payments and suspension"><p>If a recurring payment fails, Razorpay may retry or suspend the mandate. TechTreasure may pause paid features, revert the account to Free, or suspend access after a failed or reversed payment. We do not guarantee that credits will be available while payment status is pending or disputed.</p></LegalSection>
      <LegalSection title="7. Cancellation and refunds"><p>You may request cancellation through the available Razorpay subscription controls or by contacting support. Cancellation normally stops future renewals; it does not automatically reverse a completed billing cycle. Refund eligibility depends on applicable law, Razorpay status, duplicate/erroneous payment evidence, service failure, and our review. Credits already consumed may be deducted from any eligible refund. Taxes, gateway fees, and promotional credits may be non-refundable where lawful.</p></LegalSection>
      <LegalSection title="8. Chargebacks and disputes"><p>Contact support before filing a chargeback so we can investigate. Unauthorized, duplicated, or incorrectly charged payments should be reported promptly with the Razorpay payment identifier. Fraudulent chargebacks, payment abuse, or misuse of trial eligibility may result in suspension and recovery of amounts owed.</p></LegalSection>
      <LegalSection title="9. Changes"><p>We may change prices, credit amounts, plan limits, or AI availability prospectively. Existing subscriptions will be handled according to applicable Razorpay notice and consent requirements. Continuing after a disclosed renewal change may constitute acceptance where permitted by law.</p></LegalSection>
      <p className="mt-8 text-sm text-neutral-500">This document is a payment-terms template, not legal advice. Have a qualified lawyer and your Razorpay account representative review refund language, GST/tax treatment, consumer rules, subscription mandates, and required business disclosures.</p>
    </LegalPage>
  );
}

function LegalPage({ title, updated, children }: { title: string; updated: string; children: React.ReactNode }) { return <main className="mx-auto max-w-3xl px-6 py-10"><Link href="/" className="font-bold text-brand">TechTreasure</Link><h1 className="mt-8 text-3xl font-bold">{title}</h1><p className="mt-2 text-sm text-neutral-500">Last updated: {updated}</p><article className="prose prose-neutral mt-8 max-w-none space-y-6 text-sm leading-7">{children}</article></main>; }
function LegalSection({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="mb-2 text-lg font-semibold text-neutral-900">{title}</h2>{children}</section>; }
